#!/bin/bash

sudo rm "./dissertation.aux"
sudo rm "./dissertation.idx"
sudo rm "./dissertation.ilg"
sudo rm "./dissertation.ind"
sudo rm "./dissertation.lof"
sudo rm "./dissertation.log"
sudo rm "./dissertation.lot"
sudo rm "./dissertation.out"
sudo rm "./dissertation.synctex.gz"
sudo rm "./dissertation.toc"
sudo rm "./dissertation.acn"
sudo rm "./dissertation.bbl"
sudo rm "./dissertation.glo"
sudo rm "./dissertation.glsdefs"
sudo rm "./dissertation.ist"
sudo rm "./dissertation.blg"
sudo rm "./dissertation.fdb_latexmk"
sudo rm "./dissertation.fls"
sudo rm "./dissertation.xdv"
sudo rm "./dissertation.ttf"
sudo rm "./dissertation.acr"
sudo rm "./dissertation.alg"
sudo rm "./dissertation.glg"
sudo rm "./dissertation.gls"
 